language: cpp

sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: linux
      dist: trusty
      sudo: required

          
before_install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]
  then
    CMAKE_FLAGS="-DCMAKE_CXX_COMPILER=g++-6 -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5"
    brew update
    brew install gcc qt5 
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]
  then
    export CMAKE_FLAGS='-DOPTION_INSTALL_PYTHONQT=ON'
    sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
    sudo apt-get update -qy
    sudo apt-get -yy install cmake qt5-default libnetpbm10-dev libhdf5-dev libfftw3-dev python-dev libhdf4-dev  g++ build-essential libtiff5-dev libgsl0-dev qtmultimedia5-dev qttools5-dev libqt5svg5-dev libqt5multimediawidgets5 qttools5-dev-tools
  fi

script:
  - cmake ${CMAKE_FLAGS} -UQT_QMAKE_EXECUTABLE -DPythonQt_Wrap_QtAll=TRUE . 
  - make 
  - make install

install:
